### ISSUE TITLE
Error when installing influx_si using conda

### ISSUE THREAD

**Issue by llegregam** [sgsokol/influx#4]
Hello,
I tried installing the new influx_si from conda (channels conda-forge and bioconda) and after installation of the v6.0.4 i could not launch the tool because I get a ModuleNotFoundError for the pandas package. When I try installing pandas manually I get conflicts with other packages...
To recreate the issue:

`conda create -n influx_si -c conda-forge -c bioconda influx_si`
`conda activate influx_si`
`influx_s -h`
`conda install pandas`

**Comment by sgsokol** [comment]
Hi,
Thanks for reporting. I could reproduce the error on my side except for installing pandas which worked for me. So package conflict must be due to your own conda installation.

For unknown reason, bioconda recipe influx_si/meta.yaml has turned back to an old version without pandas neither r-kvh. A patch-request has been submitted to bioconda. When it will be accepted, the error should be gone. I'll keep you informed.

**Comment by sgsokol** [comment]
A new recipe which includes pandas and r-kvh was tested and accepted on bioconda https://github.com/bioconda/bioconda-recipes/pull/36006. A new package was build (cf. https://anaconda.org/bioconda/influx_si/files , note "_1" in the most recent build). However, this build is not yet available in the channel repo https://conda.anaconda.org/bioconda/noarch/
I have no idea how frequently this repo is updated. Let hope one day or two.
Anyway, when updating to this new build, check that "pyhdfd78af_1" (with "_1" and not "_0" at the end) is present in the "Build" column.

**Comment by sgsokol** [comment]
A message on July 29 10:33 from Devon Ryan @dpryan79 https://gitter.im/bioconda/Lobby says that the anaconda sync service is down. We'll have to wait more some time :(

**Comment by sgsokol** [comment]
The bioconda repo is now updated, so the influx_si installation worked as expected ion my side.
