### ISSUE TITLE
Input labels don't sum up to 1

### ISSUE THREAD

**Issue by llegregam** [sgsokol/influx#5]
I have an error for which I cannot understand the source:
"Input labeled metabolite 'M.akg.c' from 'MIN_M.icit.c' sums up to a value greater than 1 at t=16.25sum-1=0.00025."

An archive containing input mtfs and results can be found here: [MIN_M.icit.c.zip](https://github.com/sgsokol/influx/files/11496633/MIN_M.icit.c.zip)

Regards,

Loïc

**Comment by sgsokol** [comment]
Input labels must sum up to 1 for every metabolite at any time point for instationary case.
It turns out that your input data from MIN_M.icit.c_labin.tsv don't obey this rule (that is what the error message says).
To see it by yourself, you can do in R:
```
df=read.csv("MIN_M.icit.c_labin.tsv", sep="\t")
sum(df[df$time==20,grep("M.akg", colnames(df))])
# which gives
# [1] 1.001
```
It means that at row corresponding to time=20, the sum is not 1 but 1.001. You have to correct your input data.

Best.

**Comment by llegregam** [comment]
Thank you for the explanation. It seems the problem came from rounding errors in the input data. Fixing them fixed the issue.
Best regard!
